### PR TITLE
Change error logging

### PR DESCRIPTION
**Pull request by arturo-seijas**
Change error loggin to leverage stack trace printing

### CODE REVIEW

**Review by mthaddon — COMMENTED** [review]
There seem to be some unrelated documentation changes here - can those be removed?

**Comment by arturo-seijas** [comment]
> There seem to be some unrelated documentation changes here - can those be removed?

Fixed that. I hadn't noticed. Thx

**Review by mthaddon — APPROVED** [review]
LGTM, thx

**Review by merkata — APPROVED** [review]
Nice!

**Pull request merged**
