### PR TITLE
Avoid running tests when only docs are changed

### PR DESCRIPTION
**Pull request by nrobinaubertin**
### Overview

Avoid running tests when only docs are changed.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation is generated using `src-docs`
- [x] The documentation for charmhub is updated.
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Review by yanksyoon — APPROVED** [review]
Nice!

**Review by jdkandersson — COMMENTED** [review]
I'm not sure this will work since we have required checks that must pass to be able to merge?

**Review by arturo-seijas — COMMENTED** [review]
How does the publishing workflow work if there's no charm to publish? Will it skip the step or break?

**Comment by nrobinaubertin** [comment]
Responding to @jdkandersson and @arturo-seijas: I thought it would retain the status of the last CI. But it did launch it again so I put the PR into draft mode again. If I cannot confirm that:
- it will not relaunch the CI
- it uses the last status of the CI
I'll will not put it into ready again.

**Comment by nrobinaubertin** [comment]
I'm closing this as I have made no progress and the issue is complex enough that we need more discussions

**Pull request closed without merging**
