### PR TITLE
Add logging during setup process and ensure we're reacting to start hook

### PR DESCRIPTION
**Pull request by mthaddon**
### Overview

We need to react to the `start` event for `_set_up_discourse` rather than the `install` event, because if a container is restarted it won't get an `install` event.

Add logging to the `_set_up_discourse` method so it's easier to see at what point during the process this is failing. In production (likely due to poor disk IO related to https://bugs.launchpad.net/juju/+bug/1989004, still to be confirmed) we're seeing issues where if containers are restarted and we can end up with the set up process failing and so discourse never being started.

This only seems possible if we enter the `_set_up_discourse` method, relations are ready and we can connect to the container, but then somewhere later on in this same method we fail to complete the setup.

This should help us track down where that's happening.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation is generated using `src-docs`
- [x] The documentation for charmhub is updated.
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Review by nrobinaubertin — DISMISSED** [review]

**Comment by nrobinaubertin** [comment]
This is probably blocked by a dependency issue that I'm trying to solve here: https://github.com/canonical/discourse-k8s-operator/pull/125

**Review by weiiwang01 — DISMISSED** [review]

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Comment by nrobinaubertin** [comment]
I have the same issue locally as https://github.com/canonical/discourse-k8s-operator/actions/runs/6632062737/job/18039459125#step:13:139

But not when I switch back to 'install' instead of 'start'

**Review by amandahla — APPROVED** [review]
LGTM

**Review by nrobinaubertin — APPROVED** [review]

**Pull request merged**
