### PR TITLE
Show Discourse version in juju status

### PR DESCRIPTION
**Pull request by arturo-seijas**
Show Discourse version in unit status

### CODE REVIEW

**Review by gregory-schiano — DISMISSED** [review]
LGTM

**Comment by gregory-schiano** [comment]
Quite minor comment, but while the CI is running the test, wouldn't it be interesting to add an assert on the exec to get the version ? That'll cover this addition in the unittests

**Comment by arturo-seijas** [comment]
> Quite minor comment, but while the CI is running the test, wouldn't it be interesting to add an assert on the exec to get the version ? That'll cover this addition in the unittests

Added

**Review by gregory-schiano — DISMISSED** [review]
LGTM

**Review by gregory-schiano — APPROVED** [review]
Last LGTM 😄

**Review by mthaddon — APPROVED** [review]

**Review by weiiwang01 — APPROVED** [review]
Nice feature! I will add this to the WordPress charm too.

**Pull request merged**
