### PR TITLE
Remove default smtp address

### PR DESCRIPTION
**Pull request by arturo-seijas**
Remove default smtp address configuration

### CODE REVIEW

**Comment by mthaddon** [comment]
What's the effect of this being empty? Might be worth mentioning that in the description in `config.yaml`.

**Review by weiiwang01 — DISMISSED** [review]

**Review by weiiwang01 — DISMISSED** [review]

**Comment by mthaddon** [comment]
> > What's the effect of this being empty? Might be worth mentioning that in the description in `config.yaml`.
> 
> The charm will reach BlockedStatus. Analogous to what happens when the `smtp_domain` config is not specified

So won't this mean that the default deployment requires us to include this option now to work in any way? We generally prefer to have charms that can deploy clean (for local testing only) without having to set any config options.

**Review by mthaddon — CHANGES_REQUESTED** [review]
Marking as needs changes because this would require anyone deploying this charm to set this option for even a local deploy for the charm to work in any way, which we'd like to avoid. If for some reason that's completely unavoidable, we should be updating the deployment instructions in the README as part of this change (and mentioning that the config option is required in`config.yaml`.

**Review by mthaddon — APPROVED** [review]
LGTM, thx

**Review by weiiwang01 — APPROVED** [review]

**Pull request merged**
